packages:
    - packages/*

onlyBuiltDependencies:
    - "@nestjs/core"
    - "@openapitools/openapi-generator-cli"
    - electron
    - esbuild
    - sharp
    - tesseract.js

supportedArchitectures:
    os:
        - win32
        - darwin
        - current
    cpu:
        - x64
        - arm64
