/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomizeRouteImport } from './routes/customize'

const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/customize': typeof CustomizeRoute
}
export interface FileRoutesByTo {
  '/customize': typeof CustomizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/customize': typeof CustomizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/customize'
  fileRoutesByTo: FileRoutesByTo
  to: '/customize'
  id: '__root__' | '/customize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomizeRoute: typeof CustomizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CustomizeRoute: CustomizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
